# Generated by Django 4.1.2 on 2022-10-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='admin',
            field=models.CharField(choices=[('Vazio', 'Vazio'), ('sim', 'sim'), ('nao', 'nao')], default='Vazio', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='permitidos',
            field=models.ManyToManyField(related_name='per', to='imoveis.imovei'),
        ),
    ]
