# Generated by Django 4.1.2 on 2022-10-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_usuario_admin_usuario_permitidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovei',
            old_name='consulta',
            new_name='consulta_img',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='permitidos',
        ),
        migrations.AddField(
            model_name='imovei',
            name='consulta_loc',
            field=models.CharField(choices=[('Vazio', 'Vazio'), ('sim', 'sim'), ('nao', 'nao')], default='Vazio', max_length=20),
        ),
        migrations.AddField(
            model_name='imovei',
            name='consulta_prec',
            field=models.CharField(choices=[('Vazio', 'Vazio'), ('sim', 'sim'), ('nao', 'nao')], default='Vazio', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='permitidos_img',
            field=models.ManyToManyField(related_name='per_img', to='imoveis.imovei'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='permitidos_loc',
            field=models.ManyToManyField(related_name='per_loc', to='imoveis.imovei'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='permitidos_prec',
            field=models.ManyToManyField(related_name='per_prec', to='imoveis.imovei'),
        ),
    ]
